# Otedama Mining Software Configuration - 2025 Edition
# Professional P2P Mining Pool with Advanced Technology Support

# Core Settings
name: "Otedama P2P Mining Pool"
version: "2.1.4"
mode: "auto"  # auto, solo, pool, p2p

# Logging Configuration
log_level: "info"  # debug, info, warn, error
logging:
  structured: true
  file: "logs/otedama.log"
  max_size: 100  # MB
  max_age: 30    # days
  max_backups: 10
  compress: true
  enable_profiling_logs: true

# Advanced Hardware Detection & Management (2025)
hardware:
  # Auto-detection settings
  auto_detection: true
  scan_interval: "300s"  # 5 minutes
  network_scan_timeout: "10s"
  
  # Detection methods
  usb_scan_enabled: true
  network_scan_enabled: true
  pcie_scan_enabled: true
  
  # Optimization settings
  auto_optimization: true
  thermal_management: true
  power_optimization: true
  frequency_scaling: true
  
  # 2025 Features
  ai_overclocking: true
  hydrocooling_support: true
  quantum_readiness: false  # Enable when available
  noise_protocol_support: true
  
  # ASIC Support (2025 Models)
  asic:
    enabled: true
    auto_detect_models: true
    supported_models:
      - "Antminer S21 Pro"        # 234 TH/s, 15 J/TH
      - "Antminer S21 XP Hydro"   # 500 TH/s, 11 J/TH  
      - "Whatsminer M63S Hydro"   # 390 TH/s, 18.5 J/TH
      - "SEALMINER A4"            # 600 TH/s, 5 J/TH (preview)
      - "Auradine Teraflux AH3880" # 288 TH/s, 12 J/TH
    
    # Thermal management
    max_temperature: 85.0          # Celsius
    thermal_shutdown_temp: 95.0    # Emergency shutdown
    cooling_curve: "aggressive"    # conservative, balanced, aggressive
    
    # Power management
    max_power_consumption: 10000   # Watts
    power_efficiency_target: 15.0  # J/TH target
    dynamic_power_scaling: true
    
  # GPU Support
  gpu:
    enabled: true
    auto_detect: true
    memory_overclock: true
    core_overclock: true
    power_target: 85  # Percentage
    fan_curve: "auto"
    
  # CPU Support
  cpu:
    enabled: true
    threads: 0  # 0 = auto-detect
    affinity: true
    huge_pages: true
    numa_optimization: true
    
  # Firmware Management
  firmware:
    auto_update: false  # Conservative default
    update_channel: "stable"  # stable, beta, dev
    repository: ""
    check_interval: "24h"

# Lightweight Profiling System (2025)
profiling:
  enabled: true
  
  # Sampling configuration
  sample_interval: "500ms"
  buffer_size: 1024  # Power of 2 for efficiency
  max_memory_mb: 64
  
  # Feature toggles
  enable_cpu_profiling: true
  enable_memory_profiling: true
  enable_hardware_profiling: true
  enable_network_profiling: true
  
  # Hardware-specific profiling
  enable_asic_metrics: true
  enable_thermal_metrics: true
  enable_power_metrics: true
  
  # Performance settings
  max_goroutines: 100
  gc_target_percent: 200  # Higher for mining workloads
  memory_limit: 4294967296  # 4GB
  
  # Alert thresholds
  high_temp_threshold: 85.0      # Celsius
  low_efficiency_threshold: 20.0  # J/TH
  high_memory_threshold: 90.0     # Percentage
  
  # Output settings
  log_interval: "60s"
  prometheus_port: 9090
  metrics_endpoint: "/metrics"

# Enhanced Stratum V2 Protocol (2025)
stratum:
  # Protocol version
  version: "v2"  # v1, v2
  enabled: true
  listen_addr: ":3333"
  
  # V2 Features
  v2:
    enable_binary_protocol: true
    enable_encryption: true
    enable_job_negotiation: true
    enable_template_selection: true
    
    # Performance optimization
    max_frame_size: 16777216  # 16MB
    compression_level: 6      # Balanced compression
    keepalive_interval: "30s"
    heartbeat_interval: "10s"
    
    # ASIC optimization
    optimize_for_asic: true
    asic_firmware_support: true
    hardware_acceleration: true
    
    # Advanced security
    require_tls13: true
    enable_hkdf: true
    enable_noise_protocol: true
    cipher_suites: []  # Default secure suites
  
  # Connection Management
  max_clients: 10000
  connection_timeout: "300s"
  read_timeout: "300s"
  write_timeout: "30s"
  buffer_size: 4096
  
  # Security
  rate_limit: 100  # requests per second
  max_message_size: 65536  # bytes
  enable_ddos_protection: true
  
  # Difficulty Management
  var_diff: true
  min_difficulty: 1.0
  max_difficulty: 1000000.0
  target_time: 10  # seconds per share
  retarget_time: "60s"
  difficulty_algorithm: "PID"  # PID controller with outlier removal
  
  # Authentication modes
  auth_mode: "zkp"  # none, static, dynamic, database, wallet, zkp

# Enhanced Zero-Knowledge Proof Authentication (2025)
zkp:
  enabled: true
  protocol: "groth16"  # groth16, plonk, stark
  curve: "bn254"      # bn254, bls12-381
  
  # Privacy settings
  identity_proof: true
  reputation_proof: true
  compliance_proof: false  # Optional regulatory compliance
  min_reputation: 0.8
  
  # Performance optimization
  proof_cache_size: 1000
  verification_threads: 4
  trusted_setup: "ceremony_2025"
  
  # Privacy features
  anonymous_mining: true
  hide_worker_identity: true
  enable_mixing: false  # Advanced privacy

# Network Configuration with Enhanced Security
network:
  listen_addr: ":30303"
  external_addr: ""  # Auto-detect if empty
  max_peers: 100
  max_connections: 1000
  dial_timeout: "15s"
  enable_ipv6: true
  enable_upnp: true
  
  # 2025 Network Features
  enable_mesh_networking: true
  enable_noise_protocol: true
  enable_quic: false  # Experimental
  
  # Bootstrap peers (production-ready addresses)
  bootstrap_peers: []  # Populated during deployment
  
  # Enhanced DDoS Protection
  ddos_protection:
    enabled: true
    max_connections_per_ip: 10
    rate_limit_per_minute: 1000
    ban_duration: "1h"
    ml_based_detection: true
    whitelist: []
    
  # Advanced security
  enable_encryption: true
  encryption_algorithm: "AES-256-GCM"
  key_rotation_interval: "24h"

# Enhanced P2P Pool Configuration
p2p_pool:
  enabled: true
  mode: "hybrid"  # pure-p2p, hybrid, federated
  
  # Pool economics
  share_difficulty: 1000.0
  min_payout: 0.001
  fee_percentage: 0.5  # Minimum sustainable fee (0.5%)
  payout_model: "FPPS"  # FPPS, PPS+, PPLNS, PROP
  
  # Consensus mechanism
  consensus:
    algorithm: "pbft"  # Practical Byzantine Fault Tolerance
    block_time: 10     # seconds
    confirmation_depth: 6
    max_byzantine_nodes: 33  # percentage
    
  # Sharechain with Byzantine Fault Tolerance
  sharechain:
    enabled: true
    block_time: "30s"
    difficulty_algorithm: "LWMA"  # Linear Weighted Moving Average
    max_shares: 10000
    sync_interval: "10s"
    
  # Automatic payouts with multi-sig
  payouts:
    enabled: true
    interval: "6h"
    min_confirmations: 10
    batch_size: 100
    multi_sig_threshold: 2
    emergency_payout_delay: "24h"
    
  # Network resilience
  mesh_networking: true
  automatic_failover: true
  peer_discovery: "dht"  # dht, static, hybrid

# Mining Configuration with 2025 Algorithms
mining:
  algorithm: "sha256d"  # sha256d, randomx, ethash, kawpow, scrypt, blake3
  hardware_type: "auto"  # auto, cpu, gpu, asic
  threads: 0  # 0 = auto-detect
  intensity: 80  # 1-100
  
  # Algorithm switching
  auto_switching: true
  profit_switching_interval: "5m"
  profit_threshold: 10  # percentage improvement required
  
  # CPU Mining with 2025 optimizations
  cpu:
    enabled: true
    threads: 0  # 0 = auto-detect
    affinity: []  # CPU core affinity
    huge_pages: true
    vector_instructions: "auto"  # auto, sse4, avx2, avx512
    cache_optimization: true
    
  # GPU Mining with latest optimizations
  gpu:
    enabled: true
    devices: []  # empty = auto-detect all
    memory_tweak: true
    power_limit: 0  # 0 = no limit (watts)
    thermal_limit: 83  # Celsius
    fan_control: "auto"
    lhr_unlock: true  # For NVIDIA LHR cards
    
  # Advanced ASIC configuration
  asic:
    enabled: true
    devices: []
    auto_frequency_scaling: true
    thermal_throttling: true
    power_management: true
    firmware_optimization: true

# Enhanced Security Configuration (2025)
security:
  # TLS Configuration
  enable_tls: true
  tls_min_version: "1.3"  # TLS 1.3 minimum
  tls_cipher_suites: []   # Use secure defaults
  
  # Certificate management
  auto_cert: false
  cert_file: ""
  key_file: ""
  ca_file: ""
  
  # Access Control
  enable_rbac: true
  max_login_attempts: 5
  login_lockout_duration: "15m"
  session_timeout: "8h"
  
  # Encryption
  encrypt_connections: true
  encrypt_storage: true
  encryption_algorithm: "AES-256-GCM"
  
  # Advanced security features
  enable_audit_logging: true
  enable_intrusion_detection: true
  enable_honeypots: false
  
  # Multi-factor authentication
  mfa:
    enabled: false
    method: "totp"  # totp, sms, email
    backup_codes: true

# Enhanced API Configuration
api:
  enabled: true
  listen_addr: ":8080"
  enable_auth: true
  enable_tls: true
  
  # API versioning
  version: "v1"
  enable_v2: false
  
  # Authentication
  auth_method: "jwt"  # jwt, api_key, oauth2
  jwt_secret: ""      # Auto-generated if empty
  jwt_expiry: "24h"
  
  # CORS
  cors:
    enabled: true
    allowed_origins: ["*"]
    allowed_methods: ["GET", "POST", "PUT", "DELETE"]
    allowed_headers: ["*"]
    
  # Rate Limiting
  rate_limit: 1000  # requests per minute
  burst_limit: 100
  
  # GraphQL support
  graphql:
    enabled: false
    playground: false
    
  # WebSocket support
  websocket:
    enabled: true
    max_connections: 1000
    ping_interval: "30s"

# Enhanced Dashboard Configuration
dashboard:
  enabled: true
  listen_addr: ":8888"
  enable_auth: false
  theme: "dark"  # dark, light, auto
  
  # Real-time updates
  update_interval: "1s"
  enable_websocket: true
  
  # Features
  show_profitability: true
  show_hardware_metrics: true
  show_network_stats: true
  show_security_alerts: true
  
  # Mobile optimization
  responsive_design: true
  pwa_support: true

# Comprehensive Monitoring (2025)
monitoring:
  enabled: true
  metrics_interval: "10s"
  
  # Prometheus integration
  prometheus:
    enabled: true
    listen_addr: ":9090"
    metrics_path: "/metrics"
    retention: "15d"
    
  # Health checks
  health_checks:
    enabled: true
    interval: "30s"
    timeout: "5s"
    
  # Alerting
  alerts:
    enabled: true
    webhook_url: ""
    email_smtp: ""
    slack_webhook: ""
    
    # Alert rules
    rules:
      - name: "High Temperature"
        condition: "temperature > 85"
        severity: "warning"
        action: "throttle"
        
      - name: "Hardware Failure"
        condition: "device_status == 'error'"
        severity: "critical"
        action: "failover"
        
      - name: "Low Efficiency"
        condition: "efficiency > 20"  # J/TH
        severity: "warning"
        action: "optimize"
  
  # Performance monitoring
  performance:
    enabled: true
    cpu_sampling: true
    memory_sampling: true
    goroutine_sampling: true
    block_sampling: true
    mutex_sampling: true

# Enhanced Storage Configuration
storage:
  data_dir: "./data"
  cache_size_mb: 512
  enable_compression: true
  compression_algorithm: "lz4"  # lz4, zstd, gzip
  
  # Database configuration
  database:
    type: "sqlite"  # sqlite, postgresql, mysql
    path: "./data/otedama.db"
    max_connections: 25
    max_idle_connections: 5
    connection_lifetime: "1h"
    
    # Performance optimization
    enable_wal: true
    cache_size: "100MB"
    temp_store: "memory"
    
    # Backup settings
    auto_backup: true
    backup_interval: "6h"
    backup_retention: "30d"

# Advanced Performance Configuration
performance:
  # Memory management
  gc_percent: 200        # Higher for mining workloads
  max_memory_mb: 0       # 0 = no limit
  memory_ballast_mb: 512 # Reduces GC pressure
  
  # CPU optimization
  gomaxprocs: 0          # 0 = use all cores
  cpu_affinity: []       # Core affinity for main process
  
  # Network optimization
  tcp_nodelay: true
  tcp_keepalive: true
  tcp_fast_open: true
  socket_buffer_size: 1048576  # 1MB
  
  # Goroutine pool
  worker_pool_size: 1000
  queue_size: 10000
  
  # Lock-free optimization
  enable_lock_free_structures: true
  atomic_operations: true

# Backup and Recovery
backup:
  enabled: true
  interval: "24h"
  retention_days: 30
  backup_dir: "./backups"
  encrypt_backups: true
  compression: "zstd"
  
  # Remote backup
  remote_backup:
    enabled: false
    type: "s3"  # s3, gcs, azure
    endpoint: ""
    bucket: ""
    access_key: ""
    secret_key: ""

# Solo Mining Configuration
solo:
  enabled: false
  wallet_address: ""
  
  # Node configuration
  node:
    url: ""
    user: ""
    password: ""
    timeout: "30s"
    
  # P2P backup
  enable_p2p_backup: true
  p2p_port: 18080

# Pool Mining Configuration
pool:
  enabled: false
  pools: []  # User-configured pool addresses
  
  # Failover configuration
  failover:
    enabled: true
    switch_threshold: 3  # failed connections
    switch_delay: "30s"

# Experimental Features (2025)
experimental:
  # Quantum resistance
  post_quantum_crypto: false
  quantum_key_distribution: false
  
  # AI optimization
  ai_difficulty_prediction: false
  ml_hardware_optimization: false
  
  # Environmental features
  carbon_tracking: true
  renewable_energy_optimization: false
  grid_balancing: false
  
  # Advanced networking
  mesh_networking: true
  satellite_backup: false
  
  # Future protocols
  stratum_v3: false
  lightning_network_integration: false

# Compliance and Legal
compliance:
  # Regulatory compliance
  gdpr_compliance: true
  ccpa_compliance: false
  kyc_required: false
  aml_monitoring: false
  
  # Tax reporting
  tax_reporting:
    enabled: false
    jurisdiction: ""
    report_interval: "annually"
    
  # Audit logging
  audit_logging:
    enabled: true
    retention_period: "2y"
    include_personal_data: false

# Development and Testing
development:
  # Debug settings
  debug_mode: false
  enable_pprof: false
  pprof_port: 6060
  
  # Testing
  enable_test_net: false
  mock_hardware: false
  simulation_mode: false
  
  # Development features
  hot_reload: false
  verbose_logging: false
