# Otedama Mining Software Configuration
# Professional P2P Mining Pool - Production Ready

# Core Settings
name: "Otedama P2P Mining Pool"
version: "3.0.0"
mode: "auto"  # auto, solo, pool, p2p

# Logging Configuration
log_level: "info"  # debug, info, warn, error
logging:
  structured: true
  file: "logs/otedama.log"
  max_size: 100  # MB
  max_age: 30    # days
  max_backups: 10
  compress: true

# Network Configuration  
network:
  listen_addr: ":30303"
  external_addr: ""  # Auto-detect if empty
  max_peers: 100
  max_connections: 1000
  dial_timeout: "15s"
  enable_ipv6: true
  enable_upnp: true
  # Real-world bootstrap peers (examples - replace with actual operational nodes)
  bootstrap_peers: []  # Will be populated during deployment
  
  # DDoS Protection
  ddos_protection:
    enabled: true
    max_connections_per_ip: 10
    rate_limit_per_minute: 1000
    ban_duration: "1h"

# Mining Configuration
mining:
  algorithm: "sha256d"  # sha256d (Bitcoin), randomx (Monero), ethash, kawpow, scrypt
  hardware_type: "auto"  # auto, cpu, gpu, asic
  threads: 0  # 0 = auto-detect
  intensity: 80  # 1-100
  
  # CPU Mining
  cpu:
    enabled: true
    threads: 0  # 0 = auto-detect
    affinity: []  # CPU core affinity
    huge_pages: true
    
  # GPU Mining  
  gpu:
    enabled: true
    devices: []  # empty = auto-detect all
    memory_tweak: false
    power_limit: 0  # 0 = no limit (watts)
    
  # ASIC Mining
  asic:
    enabled: true
    devices: []

# Zero-Knowledge Proof Authentication (Practical Implementation)
zkp:
  enabled: false  # Disabled by default for production stability
  protocol: "groth16"  # groth16, plonk
  curve: "bn254"  # bn254, bls12-381
  
  # Proof Requirements
  require_identity_proof: false
  require_reputation_proof: false
  min_reputation: 0.0
  
  # Privacy Features
  anonymous_mining: false
  hide_worker_identity: false

# P2P Pool Configuration
p2p_pool:
  enabled: true
  share_difficulty: 1000.0
  min_payout: 0.001
  fee_percentage: 1.0
  payout_model: "FPPS"  # FPPS (Full Pay Per Share) - Industry standard 2025
  
  # Sharechain Configuration
  sharechain:
    enabled: true
    block_time: "30s"
    difficulty_algorithm: "LWMA"  # Linear Weighted Moving Average
    max_shares: 10000
    
  # Automatic Payouts
  payouts:
    enabled: true
    interval: "6h"
    min_confirmations: 10
    batch_size: 100

# Stratum Server Configuration
stratum:
  enabled: true
  listen_addr: ":3333"
  protocol_version: 2  # Stratum V2 - 2025 standard
  
  # Connection Management
  max_clients: 10000
  connection_timeout: "300s"
  keepalive_interval: "30s"
  
  # Difficulty Management
  var_diff: true
  min_difficulty: 1.0
  max_difficulty: 1000000.0
  target_time: 10  # seconds per share
  retarget_time: "60s"
  
  # Authentication
  enable_worker_auth: true
  enable_zkp_auth: false

# API Configuration
api:
  enabled: true
  listen_addr: ":8080"
  enable_auth: false
  enable_tls: false
  
  # CORS
  cors:
    enabled: true
    allowed_origins: ["*"]
    allowed_methods: ["GET", "POST"]
    
  # Rate Limiting
  rate_limit: 1000  # requests per minute
  
# Dashboard Configuration
dashboard:
  enabled: true
  listen_addr: ":8888"
  enable_auth: false
  theme: "dark"
  update_interval: "1s"

# Monitoring Configuration
monitoring:
  enabled: true
  metrics_interval: "10s"
  
  # Prometheus Metrics
  prometheus:
    enabled: true
    listen_addr: ":9090"
    metrics_path: "/metrics"
    
  # Health Checks
  health_checks:
    enabled: true
    interval: "30s"
    timeout: "5s"

# Security Configuration
security:
  enable_tls: false
  tls_min_version: "1.3"  # TLS 1.3 minimum for 2025
  
  # Access Control
  enable_rbac: false
  max_login_attempts: 5
  login_lockout_duration: "15m"
  
  # Encryption
  encrypt_connections: false
  encrypt_storage: false

# Storage Configuration
storage:
  data_dir: "./data"
  cache_size_mb: 100
  enable_compression: true
  
  # Database
  database:
    type: "sqlite"  # sqlite, postgresql
    path: "./data/otedama.db"
    max_connections: 10

# Performance Configuration
performance:
  # Memory Management
  gc_percent: 100
  max_memory_mb: 0  # 0 = no limit
  
  # CPU Optimization
  gomaxprocs: 0  # 0 = use all cores
  
  # Network Optimization
  tcp_nodelay: true
  tcp_keepalive: true
  socket_buffer_size: 65536

# Backup Configuration
backup:
  enabled: false
  interval: "24h"
  retention_days: 30
  backup_dir: "./backups"
  encrypt_backups: false

# Solo Mining Configuration (for single miners)
solo:
  enabled: false
  wallet_address: ""
  node_url: ""
  node_user: ""
  node_password: ""

# Pool Mining Configuration (connect to external pools)
pool:
  enabled: false
  pools: []  # Will be configured by users with actual pool addresses
