# Simple Mining Pool Configuration

# Pool settings
pool:
  min_payout: 0.001        # Minimum payout amount
  payout_interval: 24h     # How often to process payouts
  fee: 1.0                 # Pool fee percentage

# Stratum servers
stratum:
  servers:
    - algorithm: SHA256d
      port: 3333
      difficulty: 16384
    - algorithm: Ethash
      port: 4444
      difficulty: 4000000000
    - algorithm: KawPow
      port: 5555
      difficulty: 1000000
    - algorithm: RandomX
      port: 6666
      difficulty: 100000
    - algorithm: Scrypt
      port: 7777
      difficulty: 65536

# Wallet addresses for pool fees
wallets:
  BTC: "bc1qxy2kgdygjrsqtzq2n0yrf2493p83kkfjhx0wlh"  # Replace with your BTC address
  ETH: "0x742d35Cc6634C0532925a3b844Bc9e7595f62b76"  # Replace with your ETH address
  RVN: "RXjLFpcqWdVHkZpCwkPSbHHT8YqXe9bVFf"          # Replace with your RVN address
  XMR: "44AFFq5kSiGBoZ4NMDwYtN18obc9AemS33DBLWs3H7otXft"  # Replace with your XMR address
  LTC: "LNjmkQpWRctydno6FheJqHYxXNgZ8gdgqK"          # Replace with your LTC address

# API settings
api:
  enabled: true
  listen_addr: ":8080"
  
# Dashboard
dashboard:
  enabled: true
  listen_addr: ":8081"

# Logging
log:
  level: info
  file: logs/otedama.log
  
# Database for share tracking
database:
  type: sqlite
  path: data/otedama.db