# Otedama Example Configuration
# Copy this file to config.yaml and modify as needed

# Basic Settings
app:
  name: "Otedama"
  mode: "development"  # development, staging, production
  log_level: "info"

# Mining Configuration
mining:
  algorithm: "sha256d"
  enable_cpu: true
  enable_gpu: false
  enable_asic: false
  
  cpu:
    threads: 4  # Set to 0 for auto-detect
    priority: "normal"
    
  gpu:
    devices: []  # Empty for auto-detect
    intensity: 20
    temperature_limit: 85

# Pool Settings
pool:
  enable: true
  address: "0.0.0.0:3333"
  max_connections: 1000
  fee_percentage: 1.0
  
  rewards:
    system: "PPLNS"
    window: 2h
    minimum_payout: 0.001
    
  backup_pools:
    - url: "stratum+tcp://pool.example.com:3333"
      user: "your_wallet.worker"
      password: "x"

# Stratum Settings
stratum:
  enable: true
  address: "0.0.0.0:3333"
  max_workers: 1000
  difficulty:
    initial: 8192
    retarget_interval: 60s

# P2P Network
p2p:
  enable: false
  port: 9333
  max_peers: 50
  bootstrap_nodes: []

# API Settings
api:
  enable: true
  address: "0.0.0.0:8080"
  cors:
    enabled: true
    origins: ["*"]
  auth:
    enabled: false
    jwt_secret: "change-this-secret"

# Monitoring
monitoring:
  metrics:
    enabled: true
    address: "0.0.0.0:9090"
  health:
    enabled: true
    address: "0.0.0.0:8081"

# Database
database:
  driver: "sqlite"
  connection_string: "./data/otedama.db"

# Storage
storage:
  data_dir: "./data"
  cache:
    enabled: true
    size: 100MB

# Logging
logging:
  level: "info"
  format: "text"
  output: "stdout"
  file:
    path: "./logs/otedama.log"
    max_size: 100MB
    max_backups: 3