# Otedama National-Scale Production Configuration
# Enterprise-grade P2P mining software for critical national infrastructure

# Application Configuration
app:
  name: "Otedama"
  mode: "production"
  log_level: "info"
  debug: false

# Mining Engine Configuration
mining:
  algorithm: "sha256d"  # sha256d, scrypt, x11, ethash, randomx
  max_devices: 10000    # Scale 1-10,000+ devices
  auto_scale: true      # Zero-touch scaling
  redundancy: 3         # N+2 redundancy
  batch_size: 64        # Optimal batch processing

# Multi-Device Support
  cpu:
    enabled: true
    threads: 0          # 0 = auto-detect
    priority: "normal"
    
  gpu:
    enabled: true
    devices: []         # Auto-detect all GPUs
    intensity: 20
    temperature_limit: 85
    
  asic:
    enabled: true
    devices: []         # Auto-discover ASICs
    poll_interval: 5s
    reconnect_delay: 10s

# Security Configuration
security:
  encryption: "AES-256-GCM"
  authentication: "HSM-based"
  compliance: "FIPS-140-2"
  zero_trust: true
  mfa_required: true
  audit_logging: true

# Performance Configuration
performance:
  latency: "<50ms"
  throughput: "1 PH/s+"
  uptime: "99.99%"
  memory_limit: "4Gi"
  cpu_limit: "2000m"

# Network Configuration
network:
  port: 8080
  ssl_port: 8081
  compression: true
  keep_alive: true
  max_connections: 10000

# Database Configuration
database:
  type: "sqlite"
  path: "/var/lib/otedama/database/otedama.db"
  backup: true
  encryption: true
  pool_size: 100

# Monitoring Configuration
monitoring:
  prometheus: true
  grafana: true
  alerting: true
  metrics_port: 9090
  health_check: true

# Logging Configuration
logging:
  level: "info"
  format: "json"
  output: "file"
  rotation: true
  max_size: "100MB"
  max_files: 10
    
  # Backup Pools
  backup_pools:
    - url: "stratum+tcp://backup1.pool.com:3333"
      user: "wallet.worker"
      password: "x"
    - url: "stratum+tcp://backup2.pool.com:3333"
      user: "wallet.worker"
      password: "x"

# Stratum Protocol
stratum:
  enable: true
  address: "0.0.0.0:3333"
  max_workers: 10000
  difficulty:
    initial: 8192
    retarget_interval: 60s
    variance_percent: 30
  extra_nonce_size: 4
  
# P2P Network Configuration
p2p:
  enable: true
  port: 9333
  max_peers: 100
  bootstrap_nodes:
    - "node1.otedama.network:9333"
    - "node2.otedama.network:9333"
  discovery:
    enable: true
    interval: 30s
  sync:
    enable: true
    batch_size: 1000

# API Configuration
api:
  enable: true
  address: "0.0.0.0:8080"
  cors:
    enabled: true
    origins: ["*"]
  auth:
    enabled: true
    jwt_secret: "change-this-secret-key-in-production"
    token_expiry: 24h
  rate_limit:
    enabled: true
    requests_per_minute: 100

# Monitoring & Metrics
monitoring:
  metrics:
    enabled: true
    address: "0.0.0.0:9090"
    namespace: "otedama"
  health:
    enabled: true
    address: "0.0.0.0:8081"
    check_interval: 10s
  alerts:
    enabled: false
    webhook_url: ""

# Security Configuration
security:
  enable_tls: false
  cert_file: "/path/to/cert.pem"
  key_file: "/path/to/key.pem"
  ddos_protection:
    enabled: true
    max_requests_per_ip: 1000
    ban_duration: 1h
  encryption:
    enabled: true
    algorithm: "AES-256-GCM"

# Database Configuration
database:
  driver: "sqlite"  # sqlite, mysql, postgresql
  connection_string: "./data/otedama.db"
  max_connections: 100
  max_idle_connections: 10
  connection_max_lifetime: 1h

# Storage Configuration
storage:
  data_dir: "./data"
  cache:
    enabled: true
    size: 1GB
    ttl: 1h
  backup:
    enabled: true
    interval: 24h
    retention: 7d

# Performance Optimization
optimization:
  memory:
    max_usage: 4GB
    gc_interval: 5m
  cpu:
    turbo_mode: false
    power_saving: false
  network:
    buffer_size: 64KB
    keep_alive: true
    
# Advanced Features
features:
  auto_update: false
  telemetry: false
  profit_switching:
    enabled: false
    check_interval: 5m
    min_profit_increase: 10  # percent
  multi_currency:
    enabled: true
    currencies: ["BTC", "ETH", "LTC"]

# Logging Configuration
logging:
  level: "info"
  format: "json"  # text, json
  output: "stdout"  # stdout, file
  file:
    path: "./logs/otedama.log"
    max_size: 100MB
    max_backups: 7
    max_age: 30d
    compress: true

# Development Settings (only in development mode)
development:
  mock_mining: false
  test_net: false
  verbose_logging: false
  profiling:
    enabled: false
    port: 6060