# Otedama Configuration

# Operation mode: solo, pool, miner, auto
mode: auto

# Logging
log_level: info

# Network settings
network:
  listen_addr: ":30303"
  max_peers: 50
  dial_timeout: 30s
  enable_p2p: true
  bootstrap_peers: []
    # Add your bootstrap peers here
    # Example: - "192.168.1.100:30303"

# Mining settings
mining:
  algorithm: sha256
  threads: 0  # 0 = auto-detect
  target_hash_rate: 0  # 0 = no limit
  enable_cpu: true
  enable_gpu: true
  enable_asic: false
  gpu_devices: []
  initial_difficulty: 0x1d00ffff
  
  # Pool settings (for miner mode)
  pools:
    - url: "stratum+tcp://pool.example.com:3333"
      user: "wallet_address"
      pass: "x"
      priority: 1

# API settings
api:
  enabled: true
  listen_addr: ":8080"
  enable_tls: false
  allow_origins:
    - "*"
  rate_limit: 100

# Dashboard settings
dashboard:
  enabled: true
  listen_addr: ":8888"
  enable_auth: false
  username: "admin"
  password: ""
  enable_tls: false
  cert_file: ""
  key_file: ""
  refresh_rate: "1s"

# Monitoring settings
monitoring:
  metrics_interval: 10s
  enable_profiler: false
  enable_tracing: false
  prometheus_addr: ":9090"

# Storage settings
storage:
  data_dir: "./data"
  cache_size: 1000
  compress_data: true
  backup_interval: 24h

# Security settings
security:
  enable_encryption: true
  enable_auth: false
  tls_min_version: "1.2"

# P2P Pool settings
p2p_pool:
  share_difficulty: 1000.0
  block_time: 10m
  payout_threshold: 0.01
  fee_percentage: 1.0

# Stratum server settings
stratum:
  enabled: true
  listen_addr: ":3333"
  max_clients: 10000
  var_diff: true
  min_diff: 100.0
  max_diff: 1000000.0
  target_time: 10  # seconds per share

# Performance optimization
performance:
  enable_optimization: true
  cpu_affinity: []
  huge_pages_enabled: false
  gc_percent: 100

# Zero Knowledge Proof settings (replaces KYC)
zkp:
  enabled: true
  proof_expiry: 24h
  require_age_proof: true
  min_age_requirement: 18
  require_hashpower_proof: true
  min_hashpower_requirement: 1000  # H/s
  require_reputation_proof: false
  min_reputation_score: 0.5
  audit_log_enabled: true
  trusted_verifiers: []
  
# Privacy settings
privacy:
  enable_tor: false
  enable_i2p: false
  anonymous_mining: true
  hide_ip_addresses: true