# Otedama Solo P2P Miner Configuration
# This configuration enables solo mining with optional P2P capabilities

# Wallet address for mining rewards (required)
wallet: "bc1qxy2kgdygjrsqtzq2n0yrf2493p83kkfjhx0wlh"

# Worker name (optional)
worker_name: "otedama-solo-1"

# Mining algorithm
algorithm: "sha256d"  # Options: sha256d, scrypt, ethash, randomx, etc.

# Number of mining threads (0 = auto-detect)
threads: 0

# Mining intensity (1-100)
intensity: 80

# Solo mining settings
node_rpc: "http://localhost:8332"  # Your full node RPC endpoint
block_polling: 5s                   # How often to check for new blocks
min_difficulty: 1.0                 # Minimum difficulty for shares

# P2P settings (optional - for distributed solo mining)
enable_p2p: false                   # Enable P2P networking
p2p_port: 18080                    # P2P listening port
bootstrap_peers: []                 # List of initial peers
# Example bootstrap peers:
# - "192.168.1.100:18080"  # Replace with actual peer addresses
# - "192.168.1.101:18080"
max_peers: 50                       # Maximum number of P2P connections

# Local share tracking
local_shares: true                  # Track shares locally for statistics
share_interval: 10s                 # Interval for local share generation
share_window: 1000                  # Number of shares to keep in memory

# Performance optimization
cpu_affinity: []                    # CPU core affinity (empty = auto)
gpu_devices: []                     # GPU device indices (empty = none)
auto_tune: true                     # Auto-tune for optimal performance

# Example configurations for different scenarios:

# === Solo Mining Only (No P2P) ===
# enable_p2p: false
# threads: 8
# intensity: 100

# === Solo with P2P Backup ===
# enable_p2p: true
# bootstrap_peers:
#   - "192.168.1.100:18080"  # Replace with actual peer addresses
#   - "192.168.1.101:18080"

# === Single GPU Mining ===
# gpu_devices: [0]
# threads: 1
# intensity: 95

# === Multi-GPU Mining ===
# gpu_devices: [0, 1, 2, 3]
# threads: 4
# intensity: 90

# === CPU Mining with Affinity ===
# cpu_affinity: [0, 1, 2, 3]  # Use first 4 cores
# threads: 4
# intensity: 75