version: '3.8'

services:
  # Main mining pool service
  pool:
    build: .
    image: otedama:latest
    container_name: otedama-pool
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - NODE_ENV=production
      - NODE_OPTIONS=--max-old-space-size=4096
    ports:
      - "3333:3333"     # Stratum v1
      - "3336:3336"     # Stratum v2
      - "8080:8080"     # API
      - "9090:9090"     # Metrics
      - "33333:33333"   # P2P
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
      - ./otedama.config.js:/app/otedama.config.js:ro
    networks:
      - otedama-network
    depends_on:
      - bitcoin
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "10"
    deploy:
      resources:
        limits:
          cpus: '4'
          memory: 8G
        reservations:
          cpus: '2'
          memory: 4G

  # Bitcoin Core node (optional - for testing)
  bitcoin:
    image: ruimarinho/bitcoin-core:latest
    container_name: otedama-bitcoin
    restart: unless-stopped
    environment:
      - BITCOIN_NETWORK=mainnet
      - BITCOIN_RPC_USER=${BITCOIN_RPC_USER}
      - BITCOIN_RPC_PASSWORD=${BITCOIN_RPC_PASSWORD}
      - BITCOIN_RPC_ALLOWIP=0.0.0.0/0
      - BITCOIN_TXINDEX=1
    ports:
      - "8332:8332"
      - "8333:8333"
    volumes:
      - bitcoin-data:/home/bitcoin/.bitcoin
    networks:
      - otedama-network
    command: >
      -printtoconsole
      -rpcbind=0.0.0.0
      -rpcallowip=0.0.0.0/0
      -server=1
      -txindex=1

  # Prometheus for monitoring
  prometheus:
    image: prom/prometheus:latest
    container_name: otedama-prometheus
    restart: unless-stopped
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus-data:/prometheus
    ports:
      - "9091:9090"
    networks:
      - otedama-network
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'

  # Grafana for visualization
  grafana:
    image: grafana/grafana:latest
    container_name: otedama-grafana
    restart: unless-stopped
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_PASSWORD:-admin}
      - GF_USERS_ALLOW_SIGN_UP=false
    volumes:
      - grafana-data:/var/lib/grafana
      - ./monitoring/grafana/dashboards:/etc/grafana/provisioning/dashboards:ro
      - ./monitoring/grafana/datasources:/etc/grafana/provisioning/datasources:ro
    ports:
      - "3000:3000"
    networks:
      - otedama-network
    depends_on:
      - prometheus

networks:
  otedama-network:
    driver: bridge

volumes:
  bitcoin-data:
  prometheus-data:
  grafana-data:
