global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'otedama-monitor'

rule_files:
  - '/etc/prometheus/alerts.yml'

scrape_configs:
  - job_name: 'otedama-pool'
    static_configs:
      - targets: ['otedama:9090']
    metrics_path: '/metrics'
    scrape_interval: 10s
    scrape_timeout: 5s

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']

  - job_name: 'redis'
    static_configs:
      - targets: ['redis-exporter:9121']

  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres-exporter:9187']

  - job_name: 'agent-system'
    static_configs:
      - targets: ['otedama:8084']
    metrics_path: '/api/metrics/stats'
    scrape_interval: 30s

alerting:
  alertmanagers:
    - static_configs:
        - targets: ['alertmanager:9093']