@echo off
REM Quick setup script for Otedama - First time setup
TITLE Otedama Quick Setup

echo ========================================
echo    Otedama - Quick Setup Wizard
echo ========================================
echo.
echo Welcome to Otedama P2P Mining Software!
echo This wizard will help you get started.
echo.

REM Check prerequisites
echo Step 1: Checking prerequisites...
echo ---------------------------------

where go >nul 2>&1
if %errorlevel% neq 0 (
    echo [X] Go is not installed
    echo.
    echo Please install Go from: https://golang.org/dl/
    echo After installation, restart this setup.
    pause
    exit /b 1
) else (
    echo [OK] Go is installed
)

REM Check for config file
if exist config.yaml (
    echo [OK] Configuration file exists
    echo.
    echo Existing configuration found.
    echo Do you want to reconfigure? (Y/N)
    set /p RECONFIG=
    if /i not "%RECONFIG%"=="Y" goto build_step
)

echo.
echo Step 2: Configuration Setup
echo ---------------------------
echo.

REM Get user inputs
echo Enter your mining pool information:
echo.

set /p POOL_URL=Pool URL (e.g., stratum+tcp://pool.example.com:3333): 
if "%POOL_URL%"=="" set POOL_URL=stratum+tcp://pool.example.com:3333

set /p WALLET=Your wallet address: 
if "%WALLET%"=="" (
    echo ERROR: Wallet address is required!
    pause
    exit /b 1
)

set /p WORKER_NAME=Worker name (default: otedama): 
if "%WORKER_NAME%"=="" set WORKER_NAME=otedama

echo.
echo Select mining algorithm:
echo 1. SHA256d (Bitcoin)
echo 2. Scrypt (Litecoin)
echo 3. Ethash (Ethereum)
echo 4. RandomX (Monero)
echo 5. CryptoNight
echo 6. X11 (Dash)
echo 7. Blake2b
echo.
set /p ALGO_CHOICE=Enter choice (1-7): 

if "%ALGO_CHOICE%"=="1" set ALGORITHM=sha256d
if "%ALGO_CHOICE%"=="2" set ALGORITHM=scrypt
if "%ALGO_CHOICE%"=="3" set ALGORITHM=ethash
if "%ALGO_CHOICE%"=="4" set ALGORITHM=randomx
if "%ALGO_CHOICE%"=="5" set ALGORITHM=cryptonight
if "%ALGO_CHOICE%"=="6" set ALGORITHM=x11
if "%ALGO_CHOICE%"=="7" set ALGORITHM=blake2b
if "%ALGORITHM%"=="" set ALGORITHM=sha256d

echo.
echo Select hardware to use:
echo 1. CPU only
echo 2. GPU only
echo 3. Both CPU and GPU
echo 4. Auto-detect (recommended)
echo.
set /p HW_CHOICE=Enter choice (1-4): 

if "%HW_CHOICE%"=="1" (
    set CPU_ENABLED=true
    set GPU_ENABLED=false
)
if "%HW_CHOICE%"=="2" (
    set CPU_ENABLED=false
    set GPU_ENABLED=true
)
if "%HW_CHOICE%"=="3" (
    set CPU_ENABLED=true
    set GPU_ENABLED=true
)
if "%HW_CHOICE%"=="4" (
    set CPU_ENABLED=true
    set GPU_ENABLED=true
)

REM Create configuration file
echo.
echo Creating configuration file...

(
echo # Otedama Configuration - Generated by Quick Setup
echo # Generated on %date% %time%
echo.
echo mining:
echo   algorithm: %ALGORITHM%
echo   auto_start: false
echo   cpu:
echo     enabled: %CPU_ENABLED%
echo     threads: 0  # auto-detect
echo   gpu:
echo     enabled: %GPU_ENABLED%
echo     intensity: 20
echo     temperature_limit: 85
echo.
echo stratum:
echo   enabled: true
echo   pools:
echo     - url: %POOL_URL%
echo       user: %WALLET%.%WORKER_NAME%
echo       password: x
echo       priority: 1
echo.
echo p2p:
echo   enable: false
echo   port: 18555
echo.
echo api:
echo   enable: true
echo   address: :8080
echo.
echo monitoring:
echo   enable: true
echo   metrics_port: 9090
echo   health_port: 8081
echo.
echo logging:
echo   level: info
echo   output: stdout
) > config.yaml

echo Configuration saved to config.yaml
echo.

:build_step
echo Step 3: Building Otedama
echo ------------------------
echo.

if exist build\bin\otedama.exe (
    echo Otedama is already built.
    echo Do you want to rebuild? (Y/N)
    set /p REBUILD=
    if /i not "%REBUILD%"=="Y" goto setup_complete
)

echo Building Otedama...
call build.bat
if %errorlevel% neq 0 (
    echo ERROR: Build failed!
    pause
    exit /b 1
)

:setup_complete
echo.
echo ========================================
echo    Setup Complete!
echo ========================================
echo.
echo Your configuration:
echo -------------------
echo Algorithm: %ALGORITHM%
echo Pool: %POOL_URL%
echo Wallet: %WALLET%
echo Worker: %WORKER_NAME%
echo.

REM Optional benchmark
echo Would you like to run a benchmark to test your hardware? (Y/N)
set /p RUN_BENCHMARK=
if /i "%RUN_BENCHMARK%"=="Y" (
    echo.
    echo Running benchmark...
    call benchmark.bat
)

echo.
echo ========================================
echo    Ready to Start Mining!
echo ========================================
echo.
echo You can now start mining with: start.bat
echo.
echo Useful commands:
echo - start.bat     : Start mining
echo - stop.bat      : Stop mining
echo - status.bat    : View status
echo - benchmark.bat : Run benchmark
echo - test.bat      : Run tests
echo.
echo Web Dashboard: http://localhost:8080
echo.

echo Would you like to start mining now? (Y/N)
set /p START_NOW=
if /i "%START_NOW%"=="Y" (
    echo.
    echo Starting Otedama...
    call start.bat
) else (
    echo.
    echo To start mining later, run: start.bat
)

echo.
pause
