apiVersion: v2
name: otedama
description: A Helm chart for Otedama P2P Mining Pool
type: application
version: 0.1.7
appVersion: "0.1.7"
home: https://otedama.io
sources:
  - https://github.com/otedama/otedama
maintainers:
  - name: Otedama Team
    email: support@otedama.io
keywords:
  - mining
  - pool
  - p2p
  - cryptocurrency
  - bitcoin
dependencies:
  - name: postgresql
    version: ~12.0.0
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
  - name: redis
    version: ~18.0.0
    repository: https://charts.bitnami.com/bitnami
    condition: redis.enabled
  - name: prometheus
    version: ~25.0.0
    repository: https://prometheus-community.github.io/helm-charts
    condition: prometheus.enabled
  - name: grafana
    version: ~7.0.0
    repository: https://grafana.github.io/helm-charts
    condition: grafana.enabled