apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: otedama-ingress
  namespace: otedama
  labels:
    app: otedama
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/websocket-services: otedama-dashboard
    nginx.ingress.kubernetes.io/proxy-body-size: "0"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "600"
spec:
  tls:
  - hosts:
    - pool.otedama.io
    - api.otedama.io
    secretName: otedama-tls
  rules:
  - host: pool.otedama.io
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: otedama-dashboard
            port:
              number: 80
  - host: api.otedama.io
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: otedama-api
            port:
              number: 8081