apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: otedama-data
  namespace: otedama
  labels:
    app: otedama
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
  storageClassName: fast-ssd