apiVersion: v1
kind: ServiceAccount
metadata:
  name: otedama
  namespace: otedama
  labels:
    app: otedama
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: otedama
  namespace: otedama
  labels:
    app: otedama
rules:
- apiGroups: [""]
  resources: ["pods", "services", "endpoints"]
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["get", "list", "watch", "create", "update", "patch"]
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: otedama
  namespace: otedama
  labels:
    app: otedama
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: otedama
subjects:
- kind: ServiceAccount
  name: otedama
  namespace: otedama