apiVersion: v1
kind: Secret
metadata:
  name: otedama-secrets
  namespace: otedama
  labels:
    app: otedama
    component: secrets
type: Opaque
stringData:
  # Database credentials
  DB_PASSWORD: "your_secure_database_password_here"
  DB_USER: "otedama"
  
  # Redis credentials
  REDIS_PASSWORD: "your_secure_redis_password_here"
  
  # Security keys
  JWT_SECRET: "your_jwt_secret_key_here_minimum_32_chars"
  API_KEY_SALT: "your_api_key_salt_here"
  ENCRYPTION_KEY: "your_32_byte_encryption_key_here"
  
  # Admin credentials
  ADMIN_USERNAME: "admin"
  ADMIN_PASSWORD: "changeme_in_production"
  
  # Federation settings
  FEDERATION_NODE_ID: "your_unique_node_id"
  FEDERATION_SECRET: "your_federation_secret_key"
  
  # External API keys
  COINGECKO_API_KEY: "your_coingecko_api_key"
  ETHERSCAN_API_KEY: "your_etherscan_api_key"
  BLOCKCHAIN_INFO_API_KEY: "your_blockchain_info_api_key"
  
  # SMTP settings
  SMTP_PASSWORD: "your_smtp_password"
  
  # SSL certificates (if needed)
  TLS_CERT: ""
  TLS_KEY: ""

---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-secrets
  namespace: otedama
  labels:
    app: postgres
    component: secrets
type: Opaque
stringData:
  POSTGRES_PASSWORD: "your_secure_database_password_here"
  POSTGRES_USER: "otedama"
  POSTGRES_DB: "otedama"

---
apiVersion: v1
kind: Secret
metadata:
  name: redis-secrets
  namespace: otedama
  labels:
    app: redis
    component: secrets
type: Opaque
stringData:
  REDIS_PASSWORD: "your_secure_redis_password_here"

---
apiVersion: v1
kind: Secret
metadata:
  name: monitoring-secrets
  namespace: otedama
  labels:
    app: monitoring
    component: secrets
type: Opaque
stringData:
  GRAFANA_ADMIN_PASSWORD: "your_grafana_admin_password"