apiVersion: v1
kind: Service
metadata:
  name: otedama-dashboard
  namespace: otedama
  labels:
    app: otedama
    component: dashboard
spec:
  type: LoadBalancer
  selector:
    app: otedama
  ports:
  - name: http
    port: 80
    targetPort: 8080
    protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: otedama-api
  namespace: otedama
  labels:
    app: otedama
    component: api
spec:
  type: ClusterIP
  selector:
    app: otedama
  ports:
  - name: http
    port: 8081
    targetPort: 8081
    protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: otedama-stratum
  namespace: otedama
  labels:
    app: otedama
    component: stratum
spec:
  type: LoadBalancer
  selector:
    app: otedama
  ports:
  - name: stratum
    port: 3333
    targetPort: 3333
    protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: otedama-p2p
  namespace: otedama
  labels:
    app: otedama
    component: p2p
spec:
  type: NodePort
  selector:
    app: otedama
  ports:
  - name: p2p
    port: 30303
    targetPort: 30303
    nodePort: 30303
    protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: otedama-metrics
  namespace: otedama
  labels:
    app: otedama
    component: monitoring
spec:
  type: ClusterIP
  selector:
    app: otedama
  ports:
  - name: metrics
    port: 9090
    targetPort: 9090
    protocol: TCP