# Prometheus configuration for Otedama monitoring

global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'otedama-production'

# Alertmanager configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - alertmanager:9093

# Load rules
rule_files:
  - '/etc/prometheus/alerts/*.yml'

# Scrape configurations
scrape_configs:
  # Otedama application metrics
  - job_name: 'otedama'
    static_configs:
      - targets: ['otedama:9090']
        labels:
          service: 'otedama-core'
    metrics_path: '/metrics'
    scrape_interval: 5s

  # Node exporter for system metrics
  - job_name: 'node'
    static_configs:
      - targets: ['node-exporter:9100']
        labels:
          service: 'system'

  # PostgreSQL exporter
  - job_name: 'postgresql'
    static_configs:
      - targets: ['postgres-exporter:9187']
        labels:
          service: 'database'

  # Redis exporter
  - job_name: 'redis'
    static_configs:
      - targets: ['redis-exporter:9121']
        labels:
          service: 'cache'

  # Nginx exporter
  - job_name: 'nginx'
    static_configs:
      - targets: ['nginx-exporter:9113']
        labels:
          service: 'proxy'

  # Blackbox exporter for endpoint monitoring
  - job_name: 'blackbox-http'
    metrics_path: /probe
    params:
      module: [http_2xx]
    static_configs:
      - targets:
          - https://api.otedama.io/health
          - https://api.otedama.io/api/v1/stats
        labels:
          service: 'endpoints'
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox-exporter:9115

  # Federation peer monitoring
  - job_name: 'federation'
    static_configs:
      - targets: ['otedama:4444']
        labels:
          service: 'federation'
    metrics_path: '/federation/metrics'

# Storage configuration
storage:
  tsdb:
    retention.time: 30d
    retention.size: 50GB

# Web configuration
web:
  enable_lifecycle: true
  enable_admin_api: true