{{- if .Values.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "otedama.fullname" . }}
  labels:
    {{- include "otedama.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "otedama.selectorLabels" . | nindent 6 }}
  policyTypes:
  - Ingress
  - Egress
  {{- if .Values.networkPolicy.ingress }}
  ingress:
    {{- range .Values.networkPolicy.ingress }}
    - from:
        {{- toYaml .from | nindent 8 }}
      {{- if .ports }}
      ports:
        {{- toYaml .ports | nindent 8 }}
      {{- else }}
      ports:
      - protocol: TCP
        port: 3333
      - protocol: TCP
        port: 8080
      - protocol: TCP
        port: 8081
      - protocol: TCP
        port: 6633
      - protocol: TCP
        port: 9090
      {{- end }}
    {{- end }}
  {{- end }}
  {{- if .Values.networkPolicy.egress }}
  egress:
    {{- toYaml .Values.networkPolicy.egress | nindent 4 }}
  {{- end }}
{{- end }}