{{- if .Values.secrets.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "otedama.fullname" . }}-secrets
  labels:
    {{- include "otedama.labels" . | nindent 4 }}
type: Opaque
stringData:
  DATABASE_URL: {{ include "otedama.postgresqlUrl" . | quote }}
  REDIS_URL: {{ include "otedama.redisUrl" . | quote }}
  JWT_SECRET: {{ .Values.secrets.jwtSecret | quote }}
  ENCRYPTION_KEY: {{ .Values.secrets.encryptionKey | quote }}
{{- end }}