---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "otedama.fullname" . }}-stratum
  labels:
    {{- include "otedama.labels" . | nindent 4 }}
    service: stratum
  {{- with .Values.service.stratum.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.stratum.type }}
  ports:
    - port: {{ .Values.service.stratum.port }}
      targetPort: stratum
      protocol: TCP
      name: stratum
  selector:
    {{- include "otedama.selectorLabels" . | nindent 4 }}
  sessionAffinity: ClientIP
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 3600
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "otedama.fullname" . }}-api
  labels:
    {{- include "otedama.labels" . | nindent 4 }}
    service: api
  {{- with .Values.service.api.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.api.type }}
  ports:
    - port: {{ .Values.service.api.port }}
      targetPort: api
      protocol: TCP
      name: api
  selector:
    {{- include "otedama.selectorLabels" . | nindent 4 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "otedama.fullname" . }}-websocket
  labels:
    {{- include "otedama.labels" . | nindent 4 }}
    service: websocket
  {{- with .Values.service.websocket.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.websocket.type }}
  ports:
    - port: {{ .Values.service.websocket.port }}
      targetPort: websocket
      protocol: TCP
      name: websocket
  selector:
    {{- include "otedama.selectorLabels" . | nindent 4 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "otedama.fullname" . }}-p2p
  labels:
    {{- include "otedama.labels" . | nindent 4 }}
    service: p2p
  {{- with .Values.service.p2p.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.p2p.type }}
  ports:
    - port: {{ .Values.service.p2p.port }}
      targetPort: p2p
      protocol: TCP
      name: p2p
      {{- if and (eq .Values.service.p2p.type "NodePort") .Values.service.p2p.nodePort }}
      nodePort: {{ .Values.service.p2p.nodePort }}
      {{- end }}
  selector:
    {{- include "otedama.selectorLabels" . | nindent 4 }}