{{- if and .Values.monitoring.enabled .Values.monitoring.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "otedama.fullname" . }}
  labels:
    {{- include "otedama.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "otedama.selectorLabels" . | nindent 6 }}
  endpoints:
  - port: metrics
    interval: {{ .Values.monitoring.serviceMonitor.interval }}
    path: {{ .Values.monitoring.serviceMonitor.path }}
    honorLabels: true
{{- end }}